[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none';"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[redirects]]
  from   = "https://lostcosmonaut-cc.netlify.com/*"
  to     = "https://lostcosmonaut.cc/:splat"
  status = 301
  force  = true
