[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """\
      base-uri 'self'; \
      block-all-mixed-content; \
      child-src 'none'; \
      default-src 'self'; \
      form-action 'none'; \
      frame-ancestors 'none'; \
      frame-src 'none'; \
      object-src 'none'; \
      script-src 'none' \
      style-src 'self'; \
      worker-src 'none'\
    """
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[redirects]]
  from   = "https://lostcosmonaut-cc.netlify.com/*"
  to     = "https://lostcosmonaut.cc/:splat"
  status = 301
  force  = true
