version: 2.1

orbs:
  node: circleci/node@4.1.0

references:
  node_version: &node_version 14.15.4
  filters: &filters
    branches:
      ignore: production

jobs:
  lint:
    executor:
      name: node/default
      tag: *node_version
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run lint tasks
          command: npm run lint

workflows:
  version: 2
  default:
    jobs:
      - lint:
          filters: *filters
      - node/test:
          version: *node_version
