name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    environment:
      name: lostcosmonaut-cc (Production)
      url: https://lostcosmonaut.cc
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: src
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: lostcosmonaut-cc
