name: Deploy to Netlify

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Trigger Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
