name: Lint and Build site

on:
  push:
    branches-ignore:
      - production

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  lint:
    name: Lint JavaScript and stylesheets
    runs-on: ubuntu-16.04
    steps:
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: always()
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.3
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        id: nmp-ci
        run: npm ci
      - name: Run lint tasks
        id: npm-run-lint
        run: npm run lint
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

  build:
    name: Build site
    runs-on: ubuntu-16.04
    steps:
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: always()
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.3
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        id: nmp-ci
        run: npm ci
      - name: Run build task
        id: npm-run-build
        run: npm run build
      - name: Test built site
        id: test-built-site
        run: test -f ./public/index.html
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
